apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: test-daemonset
spec:
  selector:
    matchLabels:
      name: test-pods
  template:
    metadata:
      labels:
        name: test-pods
    spec:
      containers:
      - name: test-pods
        image: nginx
