apiVersion: v1
kind: Pod
metadata:
  name: nginx-affinity2
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disk
            operator: NotIn
            values:
            - hdd1
  containers:
  - name: nginx
    image: nginx

