apiVersion: v1
kind: Pod
metadata:
  name: newserver-web2
spec:
  containers:
  - name: newserver-web2
    image: nginx:latest
    resources:
      requests:
        memory: "128Mi"
        cpu: "0.5"
      limits:
        memory: "128Mi"
        cpu: "1"
  # Add other specifications like volumes if needed
